---
- name: Setup app-server
  hosts: app
  become: yes
  roles:
    - docker
    - app
    - zabbix-agent

- name: Setup monitoring-server
  hosts: monitoring
  become: yes
  roles:
    - docker
    - zabbix-server
